export const componetes = {
    FORM_SUCCESS : "FORM_SUCCESS",
    FORM_FAILURE : "FORM_FAILURE",
    FORM_REQUEST : "FORM_REQUEST",
    FORM_REGISTRATION : "FORM_REGISTRATION",
    FORM_LOGIN  : "FORM_LOGIN",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    GITHUB_SEARCH : "GITHUB_SEARCH"
}